version: '3.8'

networks:
  sonar-net:
    driver: bridge

services:
  sonarqube:
    container_name: sonarqube
    image: sonarqube:9.8.0-community
    ports:
      - 9000:9000
    networks:
      - sonar-net