version: '3.8'

networks:
  postgresql:
    driver: bridge

services:
  postgresql-db:
    container_name: postgresql-db
    image: postgres:latest
    hostname: postgresql
    networks:
      - postgresql
    environment:
      - POSTGRES_PASSWORD=aldev@2004
    ports:
      - 5432:5432
