version: '3.8'

networks:
  mysql-net:
    name: mysql-net
    driver: bridge

services:
  mysql:
    hostname: localhost
    image: mysql:latest
    container_name: mysql-db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=aldev@2004
    ports:
      - 3306:3306
    networks:
      - mysql-net
  phpmyadmin:
    hostname: localhost
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    networks:
      - mysql-net
    environment:
      - PMA_HOST=localhost:3306
    ports:
      - 81:80